var BeeSettings = {
  "appName": "B-NOVO",
  "version": "1.45",
  "logoImage": "images/logo1.gif",
  "logoOpen": "http://www.butent.com",
  "providerSensitivityMillis": 300,
  "providerRepeatMillis": 200,
  "providerMinPrefetchSteps": 1,
  "providerMaxPrefetchSteps": 100,
  "logCapacity": 10000,
  "minimizeNumberOfConcurrentRequests": true,
  "showUserPhoto": true,
  "onStartup": {"content": "grid_AssessmentRequests", "force": "*"},
  "applianceHeaderHeight": 35,
  "viewHeaderHeight": 52,
  "clickSensitivityMillis": 100,
  "clickSensitivityDistance": 10,
  "gridCellHeaderHeight": 34,
  "gridCellBodyHeight": 43
};