var BeeSettings = {
  "appName": "B-NOVO",
  "version": "2.120",
  "licence": "B-1.0/2015042401/1945",
  "build": "",
  "releaseDate": "2017.05.09",
  "logoImage": "images/logo_white.png",
  "logoOpen": "http://www.b-novo.lt",
  "providerSensitivityMillis": 300,
  "providerRepeatMillis": 200,
  "providerMinPrefetchSteps": 1,
  "providerMaxPrefetchSteps": 100,
  "loadingStateDelayMillis": 300,
  "logCapacity": 10000,
  "minimizeNumberOfConcurrentRequests": true,
  "showCommands": "mail, users, chat, company_structure",
  "userPanel": {
    "default": "NotificationUserPanel",
    "showUserPhoto": true,
    "showUserPresence": true,
    "showLogout": true},
  "onStartup": {"content": "form_AnnouncementsBoard", "force": "*"},
  "clickSensitivityMillis": 100,
  "clickSensitivityDistance": 10,
  "actionSensitivityMillis": 500,
  "newsRefreshIntervalSeconds": 60,
  "dialogResizerWidth": 6,
  "reducedInteractionStatusMinutes": 15,
  "incomingChatMessageSound": "notification.wav",
  "incomingChatMessageVolume": 0.5,
  "exporterInputStepRows": 100,
  "exporterOutputStepRows": 1000,
  "exporterSplitRowsThreshold": 1000,
  "dataSelectorInputDelayMillis": "500, 500, 400, 300, 200",
  "dataSelectorInstantSearchMaxRows": 100000,
  "dataSelectorCachingMaxRows": 100000,
  "showGridFilterCommand": false,
  "gridEditWindow": "on-top",
  "gridNewRowWindow": "on-top",
  "childEditWindow": "modal",
  "childNewRowWindow": "modal",
  "relationEditWindow": "new-tab",
  "relationNewRowWindow": "modal",
  "otherEditWindows": "new-tab",
  "otherNewRowWindows": "modal",
  "newMailMessageWindow": "detached",
  "theme" : {
    "WorkspaceMarginRight": 25,
    "ViewHeaderHeight": "600, 30, 1200, 52",
    "ChildViewHeaderHeight": "30",
    "ViewActionCreateNew": true,
    "GridActionCreateNew": true,
    "ChildActionCreateNew": true,
    "ActionSaveLarge": false,
    "GridHeaderRowHeight": "600, 24, 1200, 34",
    "GridBodyRowHeight": "600, 21, 1200, 43",
    "GridMarginLeft": 10,
    "GridFooterFont": "bold",
    "ChildGridHeaderRowHeight": "24",
    "ChildGridBodyRowHeight": "600, 20, 1200, 25",
    "ChildGridMarginLeft": 10,
    "ChildGridFooterFont": "bold",
    "ApplianceHeaderHeight": 35,
    "SubMenuLineHeight": 30,
    "WorkspaceTabHeight": 36,
    "InputLineHeight": 25,
    "InputPadding": "1px 10px",
    "ListSize1Padding": "5px 8px"
  }
};
