var BeeSettings = {
  "appName": "B-NOVO",
  "version": "1.45",
  "logoImage": "images/logo_white.png",
  "logoOpen": "http://www.butent.com",
  "providerSensitivityMillis": 300,
  "providerRepeatMillis": 200,
  "providerMinPrefetchSteps": 1,
  "providerMaxPrefetchSteps": 100,
  "logCapacity": 10000,
  "minimizeNumberOfConcurrentRequests": true,
  "showUserPhoto": true,
  "onStartup": {"content": "form_AnnouncementsBoard", "force": "*"},
  "clickSensitivityMillis": 100,
  "clickSensitivityDistance": 10,
  "theme" : {
    "WorkspaceMarginRight": 25,
    "ViewHeaderHeight": 52,
    "ChildViewHeaderHeight": 52,
    "ViewActionCreateNew": true,
    "GridActionCreateNew": true,
    "ChildActionCreateNew": true,
    "GridHeaderRowHeight": 34,
    "GridBodyRowHeight": 43,
    "GridMarginLeft": 10,
    "GridBodyFont": "14px",
    "GridFooterFont": "bold 14px",
    "ChildGridHeaderRowHeight": 34,
    "ChildGridBodyRowHeight": 43,
    "ChildGridMarginLeft": 10,
    "ChildGridBodyFont": "14px",
    "ChildGridFooterFont": "bold 14px",
    "ApplianceHeaderHeight": 35,
    "SubMenuLineHeight": 30,
    "WorkspaceTabHeight": 36,
    "TabbedPagesTabHeight": 60,
    "DisclosureClosedHeight": 55,
    "InputLineHeight": 25,
    "InputPadding": "1px 10px",
    "ListSize1Padding": "0 5px",
    "FormCellPaddingTop": 20
  }
};