
package lt.locator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReportProviderInterface", targetNamespace = "http://soap.wsbridge.ws.loctracker.msc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportProviderInterface {


    /**
     * 
     * @param timeFrom
     * @param vehicleRegistrationNumber
     * @param password
     * @param timeTo
     * @param timeZone
     * @param includeCountrySplit
     * @param userName
     * @param locale
     * @param deviceName
     * @param includeDaySplit
     * @return
     *     returns lt.locator.ReportSummarizedPeriod
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSummarizedReport", targetNamespace = "http://soap.wsbridge.ws.loctracker.msc/", className = "lt.locator.GetSummarizedReport")
    @ResponseWrapper(localName = "getSummarizedReportResponse", targetNamespace = "http://soap.wsbridge.ws.loctracker.msc/", className = "lt.locator.GetSummarizedReportResponse")
    @Action(input = "http://soap.wsbridge.ws.loctracker.msc/ReportProviderInterface/getSummarizedReportRequest", output = "http://soap.wsbridge.ws.loctracker.msc/ReportProviderInterface/getSummarizedReportResponse")
    public ReportSummarizedPeriod getSummarizedReport(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "timeFrom", targetNamespace = "")
        String timeFrom,
        @WebParam(name = "timeTo", targetNamespace = "")
        String timeTo,
        @WebParam(name = "vehicleRegistrationNumber", targetNamespace = "")
        String vehicleRegistrationNumber,
        @WebParam(name = "deviceName", targetNamespace = "")
        String deviceName,
        @WebParam(name = "includeDaySplit", targetNamespace = "")
        Boolean includeDaySplit,
        @WebParam(name = "includeCountrySplit", targetNamespace = "")
        Boolean includeCountrySplit,
        @WebParam(name = "timeZone", targetNamespace = "")
        String timeZone,
        @WebParam(name = "locale", targetNamespace = "")
        String locale);

}
