
package lt.locator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Report", targetNamespace = "http://loctracker.lt", wsdlLocation = "https://locator.lt/LoctrackerService/SOAP/Report?wsdl")
public class Report
    extends Service
{

    private final static URL REPORT_WSDL_LOCATION;
    private final static WebServiceException REPORT_EXCEPTION;
    private final static QName REPORT_QNAME = new QName("http://loctracker.lt", "Report");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://locator.lt/LoctrackerService/SOAP/Report?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORT_WSDL_LOCATION = url;
        REPORT_EXCEPTION = e;
    }

    public Report() {
        super(__getWsdlLocation(), REPORT_QNAME);
    }

    public Report(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORT_QNAME, features);
    }

    public Report(URL wsdlLocation) {
        super(wsdlLocation, REPORT_QNAME);
    }

    public Report(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORT_QNAME, features);
    }

    public Report(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Report(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReportProviderInterface
     */
    @WebEndpoint(name = "ReportProviderImplPort")
    public ReportProviderInterface getReportProviderImplPort() {
        return super.getPort(new QName("http://loctracker.lt", "ReportProviderImplPort"), ReportProviderInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportProviderInterface
     */
    @WebEndpoint(name = "ReportProviderImplPort")
    public ReportProviderInterface getReportProviderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://loctracker.lt", "ReportProviderImplPort"), ReportProviderInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORT_EXCEPTION!= null) {
            throw REPORT_EXCEPTION;
        }
        return REPORT_WSDL_LOCATION;
    }

}
