package pl.motonet;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSMotoOferta", targetNamespace = "http://moto-profil.pl/", wsdlLocation = "https://195.242.186.3/MotoBiznesWS/WSMotoOferta.asmx?WSDL")
public class WSMotoOferta extends Service {

  public static final URL WSMOTOOFERTA_WSDL_LOCATION;
  private static final Logger logger = Logger.getLogger(pl.motonet.WSMotoOferta.class.getName());

  static {
    URL url = null;
    try {
      url = new URL("https://195.242.186.3/MotoBiznesWS/WSMotoOferta.asmx?WSDL");
    } catch (MalformedURLException e) {
      logger
          .warning("Failed to create URL for the wsdl Location: "
              + "'https://195.242.186.3/MotoBiznesWS/WSMotoOferta.asmx?WSDL', "
              + "retrying as a local file");
      logger.warning(e.getMessage());
    }
    WSMOTOOFERTA_WSDL_LOCATION = url;
  }

  public WSMotoOferta() {
    super(WSMOTOOFERTA_WSDL_LOCATION, new QName("http://moto-profil.pl/", "WSMotoOferta"));
  }

  public WSMotoOferta(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  /**
   * 
   * @return returns WSMotoOfertaSoap
   */
  @WebEndpoint(name = "WSMotoOfertaSoap")
  public WSMotoOfertaSoap getWSMotoOfertaSoap() {
    return super.getPort(new QName("http://moto-profil.pl/", "WSMotoOfertaSoap"),
        WSMotoOfertaSoap.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *          Supported features not in the <code>features</code> parameter will have their default
   *          values.
   * @return returns WSMotoOfertaSoap
   */
  @WebEndpoint(name = "WSMotoOfertaSoap")
  public WSMotoOfertaSoap getWSMotoOfertaSoap(WebServiceFeature... features) {
    return super.getPort(new QName("http://moto-profil.pl/", "WSMotoOfertaSoap"),
        WSMotoOfertaSoap.class, features);
  }

  /**
   * 
   * @return returns WSMotoOfertaSoap
   */
  @WebEndpoint(name = "WSMotoOfertaSoap12")
  public WSMotoOfertaSoap getWSMotoOfertaSoap12() {
    return super.getPort(new QName("http://moto-profil.pl/", "WSMotoOfertaSoap12"),
        WSMotoOfertaSoap.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *          Supported features not in the <code>features</code> parameter will have their default
   *          values.
   * @return returns WSMotoOfertaSoap
   */
  @WebEndpoint(name = "WSMotoOfertaSoap12")
  public WSMotoOfertaSoap getWSMotoOfertaSoap12(WebServiceFeature... features) {
    return super.getPort(new QName("http://moto-profil.pl/", "WSMotoOfertaSoap12"),
        WSMotoOfertaSoap.class, features);
  }

}
