package pl.motonet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebService(name = "WSMotoOfertaSoap", targetNamespace = "http://moto-profil.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSMotoOfertaSoap {

  /**
   * 
   * @param aktualnaWersja
   * @return returns byte[]
   */
  @WebMethod(operationName = "PobierzNowaWersjeOferta", action = "http://moto-profil.pl/PobierzNowaWersjeOferta")
  @WebResult(name = "PobierzNowaWersjeOfertaResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "PobierzNowaWersjeOferta", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.PobierzNowaWersjeOferta")
  @ResponseWrapper(localName = "PobierzNowaWersjeOfertaResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.PobierzNowaWersjeOfertaResponse")
  public byte[] pobierzNowaWersjeOferta(
      @WebParam(name = "aktualna_wersja", targetNamespace = "http://moto-profil.pl/") String aktualnaWersja);

  /**
   * 
   * @param fiks
   * @param nrKontrahentaMotonet
   * @return returns pl.motonet.ArrayOfString
   */
  @WebMethod(operationName = "PobierzSiatkeRabatow", action = "http://moto-profil.pl/PobierzSiatkeRabatow")
  @WebResult(name = "PobierzSiatkeRabatowResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "PobierzSiatkeRabatow", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.PobierzSiatkeRabatow")
  @ResponseWrapper(localName = "PobierzSiatkeRabatowResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.PobierzSiatkeRabatowResponse")
  public ArrayOfString pobierzSiatkeRabatow(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "nr_kontrahenta_motonet", targetNamespace = "http://moto-profil.pl/") String nrKontrahentaMotonet);

  /**
   * 
   * @param aktualnaWersja
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "SprawdzNowaWersjeOferta", action = "http://moto-profil.pl/SprawdzNowaWersjeOferta")
  @WebResult(name = "SprawdzNowaWersjeOfertaResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "SprawdzNowaWersjeOferta", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.SprawdzNowaWersjeOferta")
  @ResponseWrapper(localName = "SprawdzNowaWersjeOfertaResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.SprawdzNowaWersjeOfertaResponse")
  public String sprawdzNowaWersjeOferta(
      @WebParam(name = "aktualna_wersja", targetNamespace = "http://moto-profil.pl/") String aktualnaWersja);

  /**
   * 
   * @param numer
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Test", action = "http://moto-profil.pl/Test")
  @WebResult(name = "TestResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "Test", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.Test")
  @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.TestResponse")
  public String test(
      @WebParam(name = "numer", targetNamespace = "http://moto-profil.pl/") String numer);

  /**
   * 
   * @param fiks
   * @param wersja
   * @param motonet
   * @param plik
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ZalogujPobranieCennika", action = "http://moto-profil.pl/ZalogujPobranieCennika")
  @WebResult(name = "ZalogujPobranieCennikaResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZalogujPobranieCennika", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZalogujPobranieCennika")
  @ResponseWrapper(localName = "ZalogujPobranieCennikaResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZalogujPobranieCennikaResponse")
  public String zalogujPobranieCennika(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "wersja", targetNamespace = "http://moto-profil.pl/") String wersja,
      @WebParam(name = "plik", targetNamespace = "http://moto-profil.pl/") String plik);

  /**
   * 
   * @param fiks
   * @param wersja
   * @param motonet
   * @param plik
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "ZalogujPobranieOferty", action = "http://moto-profil.pl/ZalogujPobranieOferty")
  @WebResult(name = "ZalogujPobranieOfertyResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZalogujPobranieOferty", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZalogujPobranieOferty")
  @ResponseWrapper(localName = "ZalogujPobranieOfertyResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZalogujPobranieOfertyResponse")
  public String zalogujPobranieOferty(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "wersja", targetNamespace = "http://moto-profil.pl/") String wersja,
      @WebParam(name = "plik", targetNamespace = "http://moto-profil.pl/") String plik);

  /**
   * Funkcja zwracaj�ca cennik w ramach oferty
   * 
   * @param fiks
   * @param wersja
   * @param motonet
   * @return returns byte[]
   */
  @WebMethod(operationName = "ZwrocCennik", action = "http://moto-profil.pl/ZwrocCennik")
  @WebResult(name = "ZwrocCennikResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZwrocCennik", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennik")
  @ResponseWrapper(localName = "ZwrocCennikResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennikResponse")
  public byte[] zwrocCennik(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "wersja", targetNamespace = "http://moto-profil.pl/") String wersja);

  /**
   * Metoda zastrze�ona
   * 
   * @param fiks
   * @param wersja
   * @param motonet
   * @return returns pl.motonet.ArrayOfString
   */
  @WebMethod(action = "http://moto-profil.pl/zwrocCennikDetalOffline")
  @WebResult(name = "zwrocCennikDetalOfflineResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "zwrocCennikDetalOffline", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennikDetalOffline")
  @ResponseWrapper(localName = "zwrocCennikDetalOfflineResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennikDetalOfflineResponse")
  public ArrayOfString zwrocCennikDetalOffline(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "wersja", targetNamespace = "http://moto-profil.pl/") String wersja);

  /**
   * Metoda zastrze�ona
   * 
   * @param fiks
   * @param wersja
   * @param formatCSV
   * @param motonet
   * @return returns pl.motonet.ArrayOfString
   */
  @WebMethod(action = "http://moto-profil.pl/zwrocCennikDetalOfflineFormat")
  @WebResult(name = "zwrocCennikDetalOfflineFormatResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "zwrocCennikDetalOfflineFormat", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennikDetalOfflineFormat")
  @ResponseWrapper(localName = "zwrocCennikDetalOfflineFormatResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocCennikDetalOfflineFormatResponse")
  public ArrayOfString zwrocCennikDetalOfflineFormat(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "wersja", targetNamespace = "http://moto-profil.pl/") String wersja,
      @WebParam(name = "formatCSV", targetNamespace = "http://moto-profil.pl/") boolean formatCSV);

  /**
   * 
   * @param fiks
   * @param nrKontrahentaMotonet
   * @return returns pl.motonet.ArrayOfString
   */
  @WebMethod(operationName = "ZwrocGrupyRabatowe", action = "http://moto-profil.pl/ZwrocGrupyRabatowe")
  @WebResult(name = "ZwrocGrupyRabatoweResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZwrocGrupyRabatowe", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocGrupyRabatowe")
  @ResponseWrapper(localName = "ZwrocGrupyRabatoweResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocGrupyRabatoweResponse")
  public ArrayOfString zwrocGrupyRabatowe(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "nr_kontrahenta_motonet", targetNamespace = "http://moto-profil.pl/") String nrKontrahentaMotonet);

  /**
   * Funkcja zwracaj�ca kolejn� paczk� danych oferty
   * 
   * @param fiks
   * @param numerPaczki
   * @param numer
   * @param motonet
   * @return returns byte[]
   */
  @WebMethod(operationName = "ZwrocPaczkeOferty", action = "http://moto-profil.pl/ZwrocPaczkeOferty")
  @WebResult(name = "ZwrocPaczkeOfertyResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZwrocPaczkeOferty", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocPaczkeOferty")
  @ResponseWrapper(localName = "ZwrocPaczkeOfertyResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocPaczkeOfertyResponse")
  public byte[] zwrocPaczkeOferty(
      @WebParam(name = "fiks", targetNamespace = "http://moto-profil.pl/") String fiks,
      @WebParam(name = "motonet", targetNamespace = "http://moto-profil.pl/") String motonet,
      @WebParam(name = "numer", targetNamespace = "http://moto-profil.pl/") String numer,
      @WebParam(name = "numer_paczki", targetNamespace = "http://moto-profil.pl/") int numerPaczki);

  /**
   * 
   * @return returns pl.motonet.ArrayOfString
   */
  @WebMethod(operationName = "ZwrocPromocjeDlaOferty", action = "http://moto-profil.pl/ZwrocPromocjeDlaOferty")
  @WebResult(name = "ZwrocPromocjeDlaOfertyResult", targetNamespace = "http://moto-profil.pl/")
  @RequestWrapper(localName = "ZwrocPromocjeDlaOferty", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocPromocjeDlaOferty")
  @ResponseWrapper(localName = "ZwrocPromocjeDlaOfertyResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocPromocjeDlaOfertyResponse")
  public ArrayOfString zwrocPromocjeDlaOferty();

  /**
   * Funkcja zwracaj�ca rozmiar oferty oraz liczb� paczek, w kt�rej oferta b�dzie zwracana
   * 
   * @param zwrocRozmiarCennikaResult
   * @param numer
   * @param liczbaPaczek
   */
  @WebMethod(operationName = "ZwrocRozmiarCennika", action = "http://moto-profil.pl/ZwrocRozmiarCennika")
  @RequestWrapper(localName = "ZwrocRozmiarCennika", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocRozmiarCennika")
  @ResponseWrapper(localName = "ZwrocRozmiarCennikaResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocRozmiarCennikaResponse")
  public void zwrocRozmiarCennika(
      @WebParam(name = "numer", targetNamespace = "http://moto-profil.pl/") String numer,
      @WebParam(name = "ZwrocRozmiarCennikaResult", targetNamespace = "http://moto-profil.pl/", mode = WebParam.Mode.OUT) Holder<Integer> zwrocRozmiarCennikaResult,
      @WebParam(name = "liczba_paczek", targetNamespace = "http://moto-profil.pl/", mode = WebParam.Mode.OUT) Holder<Integer> liczbaPaczek);

  /**
   * Funkcja zwracaj�ca rozmiar oferty oraz liczb� paczek, w kt�rej oferta b�dzie zwracana
   * 
   * @param numer
   * @param liczbaPaczek
   * @param zwrocRozmiarOfertyResult
   */
  @WebMethod(operationName = "ZwrocRozmiarOferty", action = "http://moto-profil.pl/ZwrocRozmiarOferty")
  @RequestWrapper(localName = "ZwrocRozmiarOferty", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocRozmiarOferty")
  @ResponseWrapper(localName = "ZwrocRozmiarOfertyResponse", targetNamespace = "http://moto-profil.pl/", className = "pl.motonet.ZwrocRozmiarOfertyResponse")
  public void zwrocRozmiarOferty(
      @WebParam(name = "numer", targetNamespace = "http://moto-profil.pl/") String numer,
      @WebParam(name = "ZwrocRozmiarOfertyResult", targetNamespace = "http://moto-profil.pl/", mode = WebParam.Mode.OUT) Holder<Integer> zwrocRozmiarOfertyResult,
      @WebParam(name = "liczba_paczek", targetNamespace = "http://moto-profil.pl/", mode = WebParam.Mode.OUT) Holder<Integer> liczbaPaczek);

}
