package com.butent.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebService(name = ButentWS.PORT, targetNamespace = ButentWS.NAMESPACE)
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ButentWebServiceSoapPort {

  /**
   * 
   * @param pwd
   * @param usr
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Login", action = ButentWS.ACTION + ".Login")
  @WebResult(name = "Result", partName = "Result")
  String login(
      @WebParam(name = "usr", partName = "usr") String usr,
      @WebParam(name = "pwd", partName = "pwd") String pwd);

  /**
   * 
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Logout", action = ButentWS.ACTION + ".Logout")
  @WebResult(name = "Result", partName = "Result")
  String logout();

  /**
   * 
   * @param mthd
   * @param prm
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Process", action = ButentWS.ACTION + ".Process")
  @WebResult(name = "Result", partName = "Result")
  String process(
      @WebParam(name = "mthd", partName = "mthd") String mthd,
      @WebParam(name = "prm", partName = "prm") String prm);

}