package com.butent.bee.shared.html.builder;

import com.butent.bee.shared.BeeConst;

public class Style {

  public static final String ALIGN_CONTENT = "align-content";
  public static final String ALIGN_ITEMS = "align-items";
  public static final String ALIGN_SELF = "align-self";
  public static final String ALIGNMENT_ADJUST = "alignment-adjust";
  public static final String ALIGNMENT_BASELINE = "alignment-baseline";
  public static final String ALL = "all";
  public static final String ANCHOR_POINT = "anchor-point";
  public static final String ANIMATION = "animation";
  public static final String ANIMATION_DELAY = "animation-delay";
  public static final String ANIMATION_DIRECTION = "animation-direction";
  public static final String ANIMATION_DURATION = "animation-duration";
  public static final String ANIMATION_FILL_MODE = "animation-fill-mode";
  public static final String ANIMATION_ITERATION_COUNT = "animation-iteration-count";
  public static final String ANIMATION_NAME = "animation-name";
  public static final String ANIMATION_PLAY_STATE = "animation-play-state";
  public static final String ANIMATION_TIMING_FUNCTION = "animation-timing-function";
  public static final String APPEARANCE = "appearance";
  public static final String AZIMUTH = "azimuth";
  public static final String BACKFACE_VISIBILITY = "backface-visibility";
  public static final String BACKGROUND = "background";
  public static final String BACKGROUND_ATTACHMENT = "background-attachment";
  public static final String BACKGROUND_CLIP = "background-clip";
  public static final String BACKGROUND_COLOR = "background-color";
  public static final String BACKGROUND_IMAGE = "background-image";
  public static final String BACKGROUND_ORIGIN = "background-origin";
  public static final String BACKGROUND_POSITION = "background-position";
  public static final String BACKGROUND_REPEAT = "background-repeat";
  public static final String BACKGROUND_SIZE = "background-size";
  public static final String BASELINE_SHIFT = "baseline-shift";
  public static final String BINDING = "binding";
  public static final String BLEED = "bleed";
  public static final String BOOKMARK_LABEL = "bookmark-label";
  public static final String BOOKMARK_LEVEL = "bookmark-level";
  public static final String BOOKMARK_STATE = "bookmark-state";
  public static final String BOOKMARK_TARGET = "bookmark-target";
  public static final String BORDER = "border";
  public static final String BORDER_BOTTOM = "border-bottom";
  public static final String BORDER_BOTTOM_COLOR = "border-bottom-color";
  public static final String BORDER_BOTTOM_LEFT_RADIUS = "border-bottom-left-radius";
  public static final String BORDER_BOTTOM_RIGHT_RADIUS = "border-bottom-right-radius";
  public static final String BORDER_BOTTOM_STYLE = "border-bottom-style";
  public static final String BORDER_BOTTOM_WIDTH = "border-bottom-width";
  public static final String BORDER_COLLAPSE = "border-collapse";
  public static final String BORDER_COLOR = "border-color";
  public static final String BORDER_IMAGE = "border-image";
  public static final String BORDER_IMAGE_OUTSET = "border-image-outset";
  public static final String BORDER_IMAGE_REPEAT = "border-image-repeat";
  public static final String BORDER_IMAGE_SLICE = "border-image-slice";
  public static final String BORDER_IMAGE_SOURCE = "border-image-source";
  public static final String BORDER_IMAGE_WIDTH = "border-image-width";
  public static final String BORDER_LEFT = "border-left";
  public static final String BORDER_LEFT_COLOR = "border-left-color";
  public static final String BORDER_LEFT_STYLE = "border-left-style";
  public static final String BORDER_LEFT_WIDTH = "border-left-width";
  public static final String BORDER_RADIUS = "border-radius";
  public static final String BORDER_RIGHT = "border-right";
  public static final String BORDER_RIGHT_COLOR = "border-right-color";
  public static final String BORDER_RIGHT_STYLE = "border-right-style";
  public static final String BORDER_RIGHT_WIDTH = "border-right-width";
  public static final String BORDER_SPACING = "border-spacing";
  public static final String BORDER_STYLE = "border-style";
  public static final String BORDER_TOP = "border-top";
  public static final String BORDER_TOP_COLOR = "border-top-color";
  public static final String BORDER_TOP_LEFT_RADIUS = "border-top-left-radius";
  public static final String BORDER_TOP_RIGHT_RADIUS = "border-top-right-radius";
  public static final String BORDER_TOP_STYLE = "border-top-style";
  public static final String BORDER_TOP_WIDTH = "border-top-width";
  public static final String BORDER_WIDTH = "border-width";
  public static final String BOTTOM = "bottom";
  public static final String BOX_DECORATION_BREAK = "box-decoration-break";
  public static final String BOX_SHADOW = "box-shadow";
  public static final String BOX_SIZING = "box-sizing";
  public static final String BREAK_AFTER = "break-after";
  public static final String BREAK_BEFORE = "break-before";
  public static final String BREAK_INSIDE = "break-inside";
  public static final String CAPTION_SIDE = "caption-side";
  public static final String CLEAR = "clear";
  public static final String CLIP = "clip";
  public static final String COLOR = "color";
  public static final String COLOR_PROFILE = "color-profile";
  public static final String COLUMN_COUNT = "column-count";
  public static final String COLUMN_FILL = "column-fill";
  public static final String COLUMN_GAP = "column-gap";
  public static final String COLUMN_RULE = "column-rule";
  public static final String COLUMN_RULE_COLOR = "column-rule-color";
  public static final String COLUMN_RULE_STYLE = "column-rule-style";
  public static final String COLUMN_RULE_WIDTH = "column-rule-width";
  public static final String COLUMN_SPAN = "column-span";
  public static final String COLUMN_WIDTH = "column-width";
  public static final String COLUMNS = "columns";
  public static final String CONTENT = "content";
  public static final String COUNTER_INCREMENT = "counter-increment";
  public static final String COUNTER_RESET = "counter-reset";
  public static final String CROP = "crop";
  public static final String CUE = "cue";
  public static final String CUE_AFTER = "cue-after";
  public static final String CUE_BEFORE = "cue-before";
  public static final String CURSOR = "cursor";
  public static final String DIRECTION = "direction";
  public static final String DISPLAY = "display";
  public static final String DOMINANT_BASELINE = "dominant-baseline";
  public static final String DROP_INITIAL_AFTER_ADJUST = "drop-initial-after-adjust";
  public static final String DROP_INITIAL_AFTER_ALIGN = "drop-initial-after-align";
  public static final String DROP_INITIAL_BEFORE_ADJUST = "drop-initial-before-adjust";
  public static final String DROP_INITIAL_BEFORE_ALIGN = "drop-initial-before-align";
  public static final String DROP_INITIAL_SIZE = "drop-initial-size";
  public static final String DROP_INITIAL_VALUE = "drop-initial-value";
  public static final String ELEVATION = "elevation";
  public static final String EMPTY_CELLS = "empty-cells";
  public static final String FIT = "fit";
  public static final String FIT_POSITION = "fit-position";
  public static final String FLEX = "flex";
  public static final String FLEX_BASIS = "flex-basis";
  public static final String FLEX_DIRECTION = "flex-direction";
  public static final String FLEX_FLOW = "flex-flow";
  public static final String FLEX_GROW = "flex-grow";
  public static final String FLEX_SHRINK = "flex-shrink";
  public static final String FLEX_WRAP = "flex-wrap";
  public static final String FLOAT = "float";
  public static final String FLOAT_OFFSET = "float-offset";
  public static final String FONT = "font";
  public static final String FONT_FEATURE_SETTINGS = "font-feature-settings";
  public static final String FONT_FAMILY = "font-family";
  public static final String FONT_KERNING = "font-kerning";
  public static final String FONT_LANGUAGE_OVERRIDE = "font-language-override";
  public static final String FONT_SIZE = "font-size";
  public static final String FONT_SIZE_ADJUST = "font-size-adjust";
  public static final String FONT_STRETCH = "font-stretch";
  public static final String FONT_STYLE = "font-style";
  public static final String FONT_SYNTHESIS = "font-synthesis";
  public static final String FONT_VARIANT = "font-variant";
  public static final String FONT_VARIANT_ALTERNATES = "font-variant-alternates";
  public static final String FONT_VARIANT_CAPS = "font-variant-caps";
  public static final String FONT_VARIANT_EAST_ASIAN = "font-variant-east-asian";
  public static final String FONT_VARIANT_LIGATURES = "font-variant-ligatures";
  public static final String FONT_VARIANT_NUMERIC = "font-variant-numeric";
  public static final String FONT_VARIANT_POSITION = "font-variant-position";
  public static final String FONT_WEIGHT = "font-weight";
  public static final String GRID_CELL = "grid-cell";
  public static final String GRID_COLUMN = "grid-column";
  public static final String GRID_COLUMN_ALIGN = "grid-column-align";
  public static final String GRID_COLUMN_SIZING = "grid-column-sizing";
  public static final String GRID_COLUMN_SPAN = "grid-column-span";
  public static final String GRID_COLUMNS = "grid-columns";
  public static final String GRID_FLOW = "grid-flow";
  public static final String GRID_ROW = "grid-row";
  public static final String GRID_ROW_ALIGN = "grid-row-align";
  public static final String GRID_ROW_SIZING = "grid-row-sizing";
  public static final String GRID_ROW_SPAN = "grid-row-span";
  public static final String GRID_ROWS = "grid-rows";
  public static final String GRID_TEMPLATE = "grid-template";
  public static final String HANGING_PUNCTUATION = "hanging-punctuation";
  public static final String HEIGHT = "height";
  public static final String HYPHENS = "hyphens";
  public static final String ICON = "icon";
  public static final String IMAGE_ORIENTATION = "image-orientation";
  public static final String IMAGE_RENDERING = "image-rendering";
  public static final String IMAGE_RESOLUTION = "image-resolution";
  public static final String IME_MODE = "ime-mode";
  public static final String INLINE_BOX_ALIGN = "inline-box-align";
  public static final String JUSTIFY_CONTENT = "justify-content";
  public static final String LEFT = "left";
  public static final String LETTER_SPACING = "letter-spacing";
  public static final String LINE_BREAK = "line-break";
  public static final String LINE_HEIGHT = "line-height";
  public static final String LINE_STACKING = "line-stacking";
  public static final String LINE_STACKING_RUBY = "line-stacking-ruby";
  public static final String LINE_STACKING_SHIFT = "line-stacking-shift";
  public static final String LINE_STACKING_STRATEGY = "line-stacking-strategy";
  public static final String LIST_STYLE = "list-style";
  public static final String LIST_STYLE_IMAGE = "list-style-image";
  public static final String LIST_STYLE_POSITION = "list-style-position";
  public static final String LIST_STYLE_TYPE = "list-style-type";
  public static final String MARGIN = "margin";
  public static final String MARGIN_BOTTOM = "margin-bottom";
  public static final String MARGIN_LEFT = "margin-left";
  public static final String MARGIN_RIGHT = "margin-right";
  public static final String MARGIN_TOP = "margin-top";
  public static final String MARKER_OFFSET = "marker-offset";
  public static final String MARKS = "marks";
  public static final String MARQUEE_DIRECTION = "marquee-direction";
  public static final String MARQUEE_LOOP = "marquee-loop";
  public static final String MARQUEE_PLAY_COUNT = "marquee-play-count";
  public static final String MARQUEE_SPEED = "marquee-speed";
  public static final String MARQUEE_STYLE = "marquee-style";
  public static final String MAX_HEIGHT = "max-height";
  public static final String MAX_LINES = "max-lines";
  public static final String MAX_WIDTH = "max-width";
  public static final String MIN_HEIGHT = "min-height";
  public static final String MIN_WIDTH = "min-width";
  public static final String MOVE_TO = "move-to";
  public static final String NAV_DOWN = "nav-down";
  public static final String NAV_INDEX = "nav-index";
  public static final String NAV_LEFT = "nav-left";
  public static final String NAV_RIGHT = "nav-right";
  public static final String NAV_UP = "nav-up";
  public static final String OPACITY = "opacity";
  public static final String ORDER = "order";
  public static final String ORPHANS = "orphans";
  public static final String OUTLINE = "outline";
  public static final String OUTLINE_COLOR = "outline-color";
  public static final String OUTLINE_OFFSET = "outline-offset";
  public static final String OUTLINE_STYLE = "outline-style";
  public static final String OUTLINE_WIDTH = "outline-width";
  public static final String OVERFLOW = "overflow";
  public static final String OVERFLOW_STYLE = "overflow-style";
  public static final String OVERFLOW_WRAP = "overflow-wrap";
  public static final String OVERFLOW_X = "overflow-x";
  public static final String OVERFLOW_Y = "overflow-y";
  public static final String PADDING = "padding";
  public static final String PADDING_BOTTOM = "padding-bottom";
  public static final String PADDING_LEFT = "padding-left";
  public static final String PADDING_RIGHT = "padding-right";
  public static final String PADDING_TOP = "padding-top";
  public static final String PAGE = "page";
  public static final String PAGE_BREAK_AFTER = "page-break-after";
  public static final String PAGE_BREAK_BEFORE = "page-break-before";
  public static final String PAGE_BREAK_INSIDE = "page-break-inside";
  public static final String PAGE_POLICY = "page-policy";
  public static final String PAUSE = "pause";
  public static final String PAUSE_AFTER = "pause-after";
  public static final String PAUSE_BEFORE = "pause-before";
  public static final String PERSPECTIVE = "perspective";
  public static final String PERSPECTIVE_ORIGIN = "perspective-origin";
  public static final String PITCH = "pitch";
  public static final String PITCH_RANGE = "pitch-range";
  public static final String PLAY_DURING = "play-during";
  public static final String POSITION = "position";
  public static final String PRESENTATION_LEVEL = "presentation-level";
  public static final String PUNCTUATION_TRIM = "punctuation-trim";
  public static final String QUOTES = "quotes";
  public static final String RENDERING_INTENT = "rendering-intent";
  public static final String RESIZE = "resize";
  public static final String REST = "rest";
  public static final String REST_AFTER = "rest-after";
  public static final String REST_BEFORE = "rest-before";
  public static final String RICHNESS = "richness";
  public static final String RIGHT = "right";
  public static final String ROTATION = "rotation";
  public static final String ROTATION_POINT = "rotation-point";
  public static final String RUBY_ALIGN = "ruby-align";
  public static final String RUBY_OVERHANG = "ruby-overhang";
  public static final String RUBY_POSITION = "ruby-position";
  public static final String RUBY_SPAN = "ruby-span";
  public static final String SIZE = "size";
  public static final String SPEAK = "speak";
  public static final String SPEAK_AS = "speak-as";
  public static final String SPEAK_HEADER = "speak-header";
  public static final String SPEAK_NUMERAL = "speak-numeral";
  public static final String SPEAK_PUNCTUATION = "speak-punctuation";
  public static final String SPEECH_RATE = "speech-rate";
  public static final String STRESS = "stress";
  public static final String STRING_SET = "string-set";
  public static final String TAB_SIZE = "tab-size";
  public static final String TABLE_LAYOUT = "table-layout";
  public static final String TARGET = "target";
  public static final String TARGET_NAME = "target-name";
  public static final String TARGET_NEW = "target-new";
  public static final String TARGET_POSITION = "target-position";
  public static final String TEXT_ALIGN = "text-align";
  public static final String TEXT_ALIGN_LAST = "text-align-last";
  public static final String TEXT_DECORATION = "text-decoration";
  public static final String TEXT_DECORATION_COLOR = "text-decoration-color";
  public static final String TEXT_DECORATION_LINE = "text-decoration-line";
  public static final String TEXT_DECORATION_SKIP = "text-decoration-skip";
  public static final String TEXT_DECORATION_STYLE = "text-decoration-style";
  public static final String TEXT_EMPHASIS = "text-emphasis";
  public static final String TEXT_EMPHASIS_COLOR = "text-emphasis-color";
  public static final String TEXT_EMPHASIS_POSITION = "text-emphasis-position";
  public static final String TEXT_EMPHASIS_STYLE = "text-emphasis-style";
  public static final String TEXT_HEIGHT = "text-height";
  public static final String TEXT_INDENT = "text-indent";
  public static final String TEXT_JUSTIFY = "text-justify";
  public static final String TEXT_OUTLINE = "text-outline";
  public static final String TEXT_OVERFLOW = "text-overflow";
  public static final String TEXT_SHADOW = "text-shadow";
  public static final String TEXT_SPACE_COLLAPSE = "text-space-collapse";
  public static final String TEXT_TRANSFORM = "text-transform";
  public static final String TEXT_UNDERLINE_POSITION = "text-underline-position";
  public static final String TEXT_WRAP = "text-wrap";
  public static final String TOP = "top";
  public static final String TRANSFORM = "transform";
  public static final String TRANSFORM_ORIGIN = "transform-origin";
  public static final String TRANSFORM_STYLE = "transform-style";
  public static final String TRANSITION = "transition";
  public static final String TRANSITION_DELAY = "transition-delay";
  public static final String TRANSITION_DURATION = "transition-duration";
  public static final String TRANSITION_PROPERTY = "transition-property";
  public static final String TRANSITION_TIMING_FUNCTION = "transition-timing-function";
  public static final String UNICODE_BIDI = "unicode-bidi";
  public static final String VERTICAL_ALIGN = "vertical-align";
  public static final String VISIBILITY = "visibility";
  public static final String VOICE_BALANCE = "voice-balance";
  public static final String VOICE_DURATION = "voice-duration";
  public static final String VOICE_FAMILY = "voice-family";
  public static final String VOICE_PITCH = "voice-pitch";
  public static final String VOICE_RANGE = "voice-range";
  public static final String VOICE_RATE = "voice-rate";
  public static final String VOICE_STRESS = "voice-stress";
  public static final String VOICE_VOLUME = "voice-volume";
  public static final String VOLUME = "volume";
  public static final String WHITE_SPACE = "white-space";
  public static final String WIDOWS = "widows";
  public static final String WIDTH = "width";
  public static final String WORD_BREAK = "word-break";
  public static final String WORD_SPACING = "word-spacing";
  public static final String WORD_WRAP = "word-wrap";
  public static final String Z_INDEX = "z-index";

  private final String name;
  private String value;

  public Style(String name, String value) {
    this.name = name;
    this.value = value;
  }

  public String build() {
    if (getValue() == null) {
      return BeeConst.STRING_EMPTY;
    } else {
      return getName() + ": \"" + getValue() + "\";";
    }
  }

  public String getName() {
    return name;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return build();
  }
}
