package lt.lb.webservices.exchangerates;

import java.util.List;

import static lt.lb.webservices.exchangerates.ExchangeRatesConstants.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebService(name = ExchangeRatesWS.NAME, targetNamespace = ExchangeRatesWS.NAMESPACE)

public interface ExchangeRatesSoapPort {

  /**
   * Returns a list of currencies.
   * 
   */
  @WebMethod(action = ExchangeRatesWS.ACTION + "/getListOfCurrencies")
  @WebResult(name = WS_RESULT_LIST_OF_CURRENCIES_RESULT, targetNamespace = ExchangeRatesWS.NAMESPACE)
  public List<Object> getListOfCurrencies();

  /**
   * Returns the current exchange rate (expressed in Litas per 1 currency unit) for the specified
   * currency.
   * 
   * @param currency
   * @return
   */
  @WebMethod(action = ExchangeRatesWS.ACTION + "/getCurrentExchangeRate")
  @WebResult(name = WS_RESULT_CURRENT_EXCHANGE_RATE_RESULT, targetNamespace = ExchangeRatesWS.NAMESPACE)
  public String getCurrentExchangeRate(
      @WebParam(name = "Currency", targetNamespace = ExchangeRatesWS.NAMESPACE) String currency);

  /**
   * Returns an exchange rate (expressed in Litas per 1 currency unit) for the specified currency
   * and date.
   * 
   */
  @WebMethod(action = ExchangeRatesWS.ACTION + "/getExchangeRate")
  @WebResult(name = WS_RESULT_EXCHANGE_RATE_RESULT, targetNamespace = ExchangeRatesWS.NAMESPACE)
  public String getExchangeRate(
      @WebParam(name = "Currency", targetNamespace = ExchangeRatesWS.NAMESPACE) String currency,
      @WebParam(name = "Date", targetNamespace = ExchangeRatesWS.NAMESPACE) String date);


  /**
   * Returns a XML formatted string containing exchange rates for the specified currency that are
   * between specified dates.
   * 
   * @param dateLow
   * @param dateHigh
   * @param currency
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "getExchangeRatesByCurrency_XmlString", action = ExchangeRatesWS.ACTION
      + "/getExchangeRatesByCurrency_XmlString")
  @WebResult(name = ExchangeRatesConstants.WS_RESULT_EXCHANGE_RATES_BY_CURRENCY_XML_STRING,
      targetNamespace = ExchangeRatesWS.NAMESPACE)
  public String getExchangeRatesByCurrencyXmlString(
      @WebParam(name = "Currency", targetNamespace = ExchangeRatesWS.NAMESPACE) String currency,
      @WebParam(name = "DateLow", targetNamespace = ExchangeRatesWS.NAMESPACE) String dateLow,
      @WebParam(name = "DateHigh", targetNamespace = ExchangeRatesWS.NAMESPACE) String dateHigh);


  /**
   * Returns a list containing exchange rates for the specified currency that are between specified
   * dates.
   * 
   * @param dateLow
   * @param dateHigh
   * @param currency
   * @return returns java.lang.List
   */
  @WebMethod(action = ExchangeRatesWS.ACTION + "/getExchangeRatesByCurrency")
  @WebResult(name = WS_RESULT_EXCHANGE_RATES_BY_CURRENCY, targetNamespace = ExchangeRatesWS.NAMESPACE)
  public List<Object> getExchangeRatesByCurrency(
      @WebParam(name = "Currency", targetNamespace = ExchangeRatesWS.NAMESPACE) String currency,
      @WebParam(name = "DateLow", targetNamespace = ExchangeRatesWS.NAMESPACE) String dateLow,
      @WebParam(name = "DateHigh", targetNamespace = ExchangeRatesWS.NAMESPACE) String dateHigh);

}
